apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app: discovery